---
- name: Update local server(slave)
  hosts: job_slave
  become: yes
  
  tasks:
  
  - name: Update test webserver
    shell: cd /var/www/html && sudo rm -rf * && git clone -b feature https://github.com/yurakorabel/task9_jenkins.git && cp -fr task9_jenkins/* ./ && sudo rm -rf task9_jenkins/
