---
- name: Update website
  hosts: website
  become: yes
  
  tasks:
  
  - name: go to apache directory
    shell: cd /var/www/html
  
  - name: Delete old files
    shell: sudo rm -rf *
  
  - name: Git clone
    shell: git clone https://github.com/yurakorabel/task9_jenkins.git
    
  - name: Copy all new files
    shell: cp -fr task9_jenkins/* ./
   
  - name: Copy all new files
    shell: sudo rm -rf task9_jenkins/
