---
- name: Update website
  hosts: website
  become: yes
  
  tasks:
  
  - name: Update website
    shell: cd /var/www/html && sudo rm -rf * && git clone https://github.com/yurakorabel/task9_jenkins.git && cp -fr task9_jenkins/* ./ && sudo rm -rf task9_jenkins/
