
---
- name: Update local server(slave)
  hosts: job_slave
  become: yes
  
  tasks:
  
  - name: Ping my server
    shell: cd /var/www/html && sudo rm -rf * && git clone https://github.com/yurakorabel/task9_jenkins.git && git checkout feature  && cp -fr task9_jenkins/* ./ && sudo rm -rf task9_jenkins/
          
